const keys = [
  { name: 'Backquote',
    class: 'key',
    row: 0,
    item: 0,
    ru: { on: 'Ё', off: 'ё' },
    eng: { on: '~', off: '`' },
  },
  { name: 'Digit1',
    class: 'key',
    row: 0,
    item: 1,
    ru: { on: '!', off: '1' },
    eng: { on: '!', off: '1' },
  },
  { name: 'Digit2',
    class: 'key',
    row: 0,
    item: 2,
    ru: { on: '"', off: '2' },
    eng: { on: '@', off: '2' },
  },
  { name: 'Digit3',
    class: 'key',
    row: 0,
    item: 3,
    ru: { on: '№', off: '3' },
    eng: { on: '#', off: '3' },
  },
  { name: 'Digit4',
    class: 'key',
    row: 0,
    item: 4,
    ru: { on: ';', off: '4' },
    eng: { on: '$', off: '4' },
  },
  { name: 'Digit5',
    class: 'key',
    row: 0,
    item: 5,
    ru: { on: '%', off: '5' },
    eng: { on: '%', off: '5' },
  },
  { name: 'Digit6',
    class: 'key',
    row: 0,
    item: 6,
    ru: { on: ':', off: '6' },
    eng: { on: '^', off: '6' },
  },
  { name: 'Digit7',
    class: 'key',
    row: 0,
    item: 7,
    ru: { on: '?', off: '7' },
    eng: { on: '&', off: '7' },
  },
  { name: 'Digit8',
    class: 'key',
    row: 0,
    item: 8,
    ru: { on: '*', off: '8' },
    eng: { on: '*', off: '8' },
  },
  { name: 'Digit9',
    class: 'key',
    row: 0,
    item: 9,
    ru: { on: '(', off: '9' },
    eng: { on: '(', off: '9' },
  },
  { name: 'Digit0',
    class: 'key',
    row: 0,
    item: 10,
    ru: { on: ')', off: '0' },
    eng: { on: ')', off: '0' },
  },
  { name: 'Minus',
    class: 'key',
    row: 0,
    item: 11,
    ru: { on: '_', off: '-' },
    eng: { on: '_', off: '-' },
  },
  { name: 'Equal',
    class: 'key',
    row: 0,
    item: 12,
    ru: { on: '+', off: '=' },
    eng: { on: '+', off: '=' },
  },
  { name: 'Backspace',
    class: 'key special-key back',
    row: 0,
    item: 13,
    ru: { on: 'backspace', off: 'backspace' },
    eng: { on: 'backspace', off: 'backspace' },
  },
  { name: 'Tab',
    class: 'key special-key tab',
    row: 1,
    item: 0,
    ru: { on: 'tab', off: 'tab' },
    eng: { on: 'tab', off: 'tab' },
  },
  { name: 'KeyQ',
    class: 'key',
    row: 1,
    item: 1,
    ru: { on: 'Й', off: 'й' },
    eng: { on: 'Q', off: 'q' },
  },
  { name: 'KeyW',
    class: 'key',
    row: 1,
    item: 2,
    ru: { on: 'Ц', off: 'ц' },
    eng: { on: 'W', off: 'w' },
  },
  { name: 'KeyE',
    class: 'key',
    row: 1,
    item: 3,
    ru: { on: 'У', off: 'у' },
    eng: { on: 'E', off: 'e' },
  },
  { name: 'KeyR',
    class: 'key',
    row: 1,
    item: 4,
    ru: { on: 'К', off: 'к' },
    eng: { on: 'R', off: 'r' },
  },
  { name: 'KeyT',
    class: 'key',
    row: 1,
    item: 5,
    ru: { on: 'Е', off: 'е' },
    eng: { on: 'T', off: 't' },
  },
  { name: 'KeyY',
    class: 'key',
    row: 1,
    item: 6,
    ru: { on: 'Н', off: 'н' },
    eng: { on: 'Y', off: 'y' },
  },
  { name: 'KeyU',
    class: 'key',
    row: 1,
    item: 7,
    ru: { on: 'Г', off: 'г' },
    eng: { on: 'U', off: 'u' },
  },
  { name: 'KeyI',
    class: 'key',
    row: 1,
    item: 8,
    ru: { on: 'Ш', off: 'ш' },
    eng: { on: 'I', off: 'i' },
  },
  { name: 'KeyO',
    class: 'key',
    row: 1,
    item: 9,
    ru: { on: 'Щ', off: 'щ' },
    eng: { on: 'O', off: 'o' },
  },
  { name: 'KeyP',
    class: 'key',
    row: 1,
    item: 10,
    ru: { on: 'З', off: 'з' },
    eng: { on: 'P', off: 'p' },
  },
  { name: 'BracketLeft',
    class: 'key',
    row: 1,
    item: 11,
    ru: { on: 'Х', off: 'х' },
    eng: { on: '{', off: '[' },
  },
  { name: 'BracketRight',
    class: 'key',
    row: 1,
    item: 12,
    ru: { on: 'Ъ', off: 'ъ' },
    eng: { on: '}', off: ']' },
  },
  { name: 'Backslash',
    class: 'key',
    row: 1,
    item: 13,
    ru: { on: '/', off: '\\' },
    eng: { on: '|', off: '\\' },
  },
  { name: 'Delete',
    class: 'key special-key del',
    row: 1,
    item: 14,
    ru: { on: 'del', off: 'del' },
    eng: { on: 'del', off: 'del' },
  },
  { name: 'CapsLock',
    class: 'key special-key caps',
    row: 2,
    item: 0,
    ru: { on: 'caps lock', off: 'caps lock' },
    eng: { on: 'caps lock', off: 'caps lock' },
  },
  { name: 'KeyA',
    class: 'key',
    row: 2,
    item: 1,
    ru: { on: 'Ф', off: 'ф' },
    eng: { on: 'A', off: 'a' },
  },
  { name: 'KeyS',
    class: 'key',
    row: 2,
    item: 2,
    ru: { on: 'Ы', off: 'ы' },
    eng: { on: 'S', off: 's' },
  },
  { name: 'KeyD',
    class: 'key',
    row: 2,
    item: 3,
    ru: { on: 'В', off: 'в' },
    eng: { on: 'D', off: 'd' },
  },
  { name: 'KeyF',
    class: 'key',
    row: 2,
    item: 4,
    ru: { on: 'А', off: 'а' },
    eng: { on: 'F', off: 'f' },
  },
  { name: 'KeyG',
    class: 'key',
    row: 2,
    item: 5,
    ru: { on: 'П', off: 'п' },
    eng: { on: 'G', off: 'g' },
  },
  { name: 'KeyH',
    class: 'key',
    row: 2,
    item: 6,
    ru: { on: 'Р', off: 'р' },
    eng: { on: 'H', off: 'h' },
  },
  { name: 'KeyJ',
    class: 'key',
    row: 2,
    item: 7,
    ru: { on: 'О', off: 'о' },
    eng: { on: 'J', off: 'j' },
  },
  { name: 'KeyK',
    class: 'key',
    row: 2,
    item: 8,
    ru: { on: 'Л', off: 'л' },
    eng: { on: 'K', off: 'k' },
  },
  { name: 'KeyL',
    class: 'key',
    row: 2,
    item: 9,
    ru: { on: 'Д', off: 'д' },
    eng: { on: 'L', off: 'l' },
  },
  { name: 'Semicolon',
    class: 'key',
    row: 2,
    item: 10,
    ru: { on: 'Ж', off: 'ж' },
    eng: { on: ':', off: ';' },
  },
  { name: 'Quote',
    class: 'key',
    row: 2,
    item: 11,
    ru: { on: 'Э', off: 'э' },
    eng: { on: '"', off: "'" },
  },
  { name: 'Enter',
    class: 'key special-key enter',
    row: 2,
    item: 12,
    ru: { on: 'enter', off: 'enter' },
    eng: { on: 'enter', off: "enter" },
  },
  { name: 'ShiftLeft',
    class: 'key special-key shiftL',
    row: 3,
    item: 0,
    ru: { on: 'shift', off: 'shift' },
    eng: { on: 'shift', off: "shift" },
  },
  { name: 'KeyZ',
    class: 'key',
    row: 3,
    item: 1,
    ru: { on: 'Я', off: 'я' },
    eng: { on: 'Z', off: 'z' },
  },
  { name: 'KeyX',
    class: 'key',
    row: 3,
    item: 2,
    ru: { on: 'Ч', off: 'ч' },
    eng: { on: 'X', off: 'x' },
  },
  { name: 'KeyC',
    class: 'key',
    row: 3,
    item: 3,
    ru: { on: 'С', off: 'с' },
    eng: { on: 'C', off: 'c' },
  },
  { name: 'KeyV',
    class: 'key',
    row: 3,
    item: 4,
    ru: { on: 'М', off: 'м' },
    eng: { on: 'V', off: 'v' },
  },
  { name: 'KeyB',
    class: 'key',
    row: 3,
    item: 5,
    ru: { on: 'И', off: 'и' },
    eng: { on: 'B', off: 'b' },
  },
  { name: 'KeyN',
    class: 'key',
    row: 3,
    item: 6,
    ru: { on: 'Т', off: 'т' },
    eng: { on: 'N', off: 'n' },
  },
  { name: 'KeyM',
    class: 'key',
    row: 3,
    item: 7,
    ru: { on: 'Ь', off: 'ь' },
    eng: { on: 'M', off: 'm' },
  },
  { name: 'Comma',
    class: 'key',
    row: 3,
    item: 8,
    ru: { on: 'Б', off: 'б' },
    eng: { on: '<', off: ',' },
  },
  { name: 'Period',
    class: 'key',
    row: 3,
    item: 9,
    ru: { on: 'Ю', off: 'ю' },
    eng: { on: '>', off: '.' },
  },
  { name: 'Slash',
    class: 'key',
    row: 3,
    item: 10,
    ru: { on: ',', off: '.' },
    eng: { on: '?', off: '/' },
  },
  { name: 'ArrowUp',
    class: 'key special-key arr-top',
    row: 3,
    item: 11,
    ru: { on: '▲', off: '▲' },
    eng: { on: '▲', off: '▲' },
  },
  { name: 'ShiftRight',
    class: 'key special-key shiftR',
    row: 3,
    item: 12,
    ru: { on: 'shift', off: 'shift' },
    eng: { on: 'shift', off: 'shift' },
  },
  { name: 'ControlLeft',
    class: 'key special-key ctrl',
    row: 4,
    item: 0,
    ru: { on: 'ctrl', off: 'ctrl' },
    eng: { on: 'ctrl', off: 'ctrl' },
  },
  { name: 'MetaLeft',
    class: 'key special-key win',
    row: 4,
    item: 1,
    ru: { on: 'win', off: 'win' },
    eng: { on: 'win', off: 'win' },
  },
  { name: 'AltLeft',
    class: 'key special-key alt',
    row: 4,
    item: 2,
    ru: { on: 'alt', off: 'alt' },
    eng: { on: 'alt', off: 'alt' },
  },
  { name: 'Space',
    class: 'key special-key space',
    row: 4,
    item: 3,
    ru: { on: ' ', off: ' ' },
    eng: { on: ' ', off: ' ' },
  },
  { name: 'AltRight',
    class: 'key special-key alt',
    row: 4,
    item: 4,
    ru: { on: 'alt', off: 'alt' },
    eng: { on: 'alt', off: 'alt' },
  },
  { name: 'ArrowLeft',
    class: 'key special-key arr-left',
    row: 4,
    item: 5,
    ru: { on: '◀', off: '◀' },
    eng: { on: '◀', off: '◀' },
  },
  { name: 'ArrowDown',
    class: 'key special-key arr-down',
    row: 4,
    item: 6,
    ru: { on: '▼', off: '▼' },
    eng: { on: '▼', off: '▼' },
  },
  { name: 'ArrowRight',
    class: 'key special-key arr-right',
    row: 4,
    item: 7,
    ru: { on: '▶', off: '▶' },
    eng: { on: '▶', off: '▶' },
  },
  { name: 'ControlRight',
    class: 'key special-key ctrl',
    row: 4,
    item: 8,
    ru: { on: 'ctrl', off: 'ctrl' },
    eng: { on: 'ctrl', off: 'ctrl' },
  },
];
