class Key {
  constructor(name, className, row, item, ruOn, ruOff, engOn, engOff) {
    this.name = name;
    this.class = className;
    this.row = row;
    this.item = item;
    this.ru = { on: ruOn, off: ruOff};
    this.eng = { on: engOn, off: engOff};
  }
}

const keys = [
  new Key('Backquote', 'key', 0, 0, 'Ё', 'ё', '~', '`'),
  new Key('Digit1', 'key', 0, 1, '!', '1', '!', '1'),
  new Key('Digit2', 'key', 0, 2, '"', '2', '@', '2'),
  new Key('Digit3', 'key', 0, 3, '№', '3', '#', '3'),
  new Key('Digit4', 'key', 0, 4, ';', '4', '$', '4'),
  new Key('Digit5', 'key', 0, 5, '%', '5', '%', '5'),
  new Key('Digit6', 'key', 0, 6, ':', '6', '^', '6'),
  new Key('Digit7', 'key', 0, 7, '?', '7', '&', '7'),
  new Key('Digit8', 'key', 0, 8, '*', '8', '*', '8'),
  new Key('Digit9', 'key', 0, 9, '(', '9', '(', '9'),
  new Key('Digit0', 'key', 0, 10, ')', '0', ')~', '0'),
  new Key('Minus', 'key', 0, 11, '_', '-', '_', '-'),
  new Key('Equal', 'key', 0, 12, '+', '=', '+', '='),
  new Key('Backspace', 'key special-key back', 0, 13, 'backspace', 'backspace', 'backspace', 'backspace'),
  new Key('Tab', 'key special-key tab', 1, 0, 'tab', 'tab', 'tab', 'tab'),
  new Key('KeyQ', 'key', 1, 1, 'Й', 'й', 'Q', 'q'),
  new Key('KeyW', 'key', 1, 2, 'Ц', 'ц', 'W', 'w'),
  new Key('KeyE', 'key', 1, 3, 'У', 'у', 'E', 'e'),
  new Key('KeyR', 'key', 1, 4, 'К', 'к', 'R', 'r'),
  new Key('KeyT', 'key', 1, 5, 'Е', 'е', 'T', 't'),
  new Key('KeyY', 'key', 1, 6, 'Н', 'н', 'Y', 'y'),
  new Key('KeyU', 'key', 1, 7, 'Г', 'г', 'U', 'u'),

  { name: 'KeyI',
    class: 'key',
    row: 1,
    item: 8,
    ru: { on: 'Ш', off: 'ш' },
    eng: { on: 'I', off: 'i' },
  },
  { name: 'KeyO',
    class: 'key',
    row: 1,
    item: 9,
    ru: { on: 'Щ', off: 'щ' },
    eng: { on: 'O', off: 'o' },
  },
  { name: 'KeyP',
    class: 'key',
    row: 1,
    item: 10,
    ru: { on: 'З', off: 'з' },
    eng: { on: 'P', off: 'p' },
  },
  { name: 'BracketLeft',
    class: 'key',
    row: 1,
    item: 11,
    ru: { on: 'Х', off: 'х' },
    eng: { on: '{', off: '[' },
  },
  { name: 'BracketRight',
    class: 'key',
    row: 1,
    item: 12,
    ru: { on: 'Ъ', off: 'ъ' },
    eng: { on: '}', off: ']' },
  },
  { name: 'Backslash',
    class: 'key',
    row: 1,
    item: 13,
    ru: { on: '/', off: '\\' },
    eng: { on: '|', off: '\\' },
  },
  { name: 'Delete',
    class: 'key special-key del',
    row: 1,
    item: 14,
    ru: { on: 'del', off: 'del' },
    eng: { on: 'del', off: 'del' },
  },
  { name: 'CapsLock',
    class: 'key special-key caps',
    row: 2,
    item: 0,
    ru: { on: 'caps lock', off: 'caps lock' },
    eng: { on: 'caps lock', off: 'caps lock' },
  },
  { name: 'KeyA',
    class: 'key',
    row: 2,
    item: 1,
    ru: { on: 'Ф', off: 'ф' },
    eng: { on: 'A', off: 'a' },
  },
  { name: 'KeyS',
    class: 'key',
    row: 2,
    item: 2,
    ru: { on: 'Ы', off: 'ы' },
    eng: { on: 'S', off: 's' },
  },
  { name: 'KeyD',
    class: 'key',
    row: 2,
    item: 3,
    ru: { on: 'В', off: 'в' },
    eng: { on: 'D', off: 'd' },
  },
  { name: 'KeyF',
    class: 'key',
    row: 2,
    item: 4,
    ru: { on: 'А', off: 'а' },
    eng: { on: 'F', off: 'f' },
  },
  { name: 'KeyG',
    class: 'key',
    row: 2,
    item: 5,
    ru: { on: 'П', off: 'п' },
    eng: { on: 'G', off: 'g' },
  },
  { name: 'KeyH',
    class: 'key',
    row: 2,
    item: 6,
    ru: { on: 'Р', off: 'р' },
    eng: { on: 'H', off: 'h' },
  },
  { name: 'KeyJ',
    class: 'key',
    row: 2,
    item: 7,
    ru: { on: 'О', off: 'о' },
    eng: { on: 'J', off: 'j' },
  },
  { name: 'KeyK',
    class: 'key',
    row: 2,
    item: 8,
    ru: { on: 'Л', off: 'л' },
    eng: { on: 'K', off: 'k' },
  },
  { name: 'KeyL',
    class: 'key',
    row: 2,
    item: 9,
    ru: { on: 'Д', off: 'д' },
    eng: { on: 'L', off: 'l' },
  },
  { name: 'Semicolon',
    class: 'key',
    row: 2,
    item: 10,
    ru: { on: 'Ж', off: 'ж' },
    eng: { on: ':', off: ';' },
  },
  { name: 'Quote',
    class: 'key',
    row: 2,
    item: 11,
    ru: { on: 'Э', off: 'э' },
    eng: { on: '"', off: "'" },
  },
  { name: 'Enter',
    class: 'key special-key enter',
    row: 2,
    item: 12,
    ru: { on: 'enter', off: 'enter' },
    eng: { on: 'enter', off: "enter" },
  },
  { name: 'ShiftLeft',
    class: 'key special-key shiftL',
    row: 3,
    item: 0,
    ru: { on: 'shift', off: 'shift' },
    eng: { on: 'shift', off: "shift" },
  },
  { name: 'KeyZ',
    class: 'key',
    row: 3,
    item: 1,
    ru: { on: 'Я', off: 'я' },
    eng: { on: 'Z', off: 'z' },
  },
  { name: 'KeyX',
    class: 'key',
    row: 3,
    item: 2,
    ru: { on: 'Ч', off: 'ч' },
    eng: { on: 'X', off: 'x' },
  },
  { name: 'KeyC',
    class: 'key',
    row: 3,
    item: 3,
    ru: { on: 'С', off: 'с' },
    eng: { on: 'C', off: 'c' },
  },
  { name: 'KeyV',
    class: 'key',
    row: 3,
    item: 4,
    ru: { on: 'М', off: 'м' },
    eng: { on: 'V', off: 'v' },
  },
  { name: 'KeyB',
    class: 'key',
    row: 3,
    item: 5,
    ru: { on: 'И', off: 'и' },
    eng: { on: 'B', off: 'b' },
  },
  { name: 'KeyN',
    class: 'key',
    row: 3,
    item: 6,
    ru: { on: 'Т', off: 'т' },
    eng: { on: 'N', off: 'n' },
  },
  { name: 'KeyM',
    class: 'key',
    row: 3,
    item: 7,
    ru: { on: 'Ь', off: 'ь' },
    eng: { on: 'M', off: 'm' },
  },
  { name: 'Comma',
    class: 'key',
    row: 3,
    item: 8,
    ru: { on: 'Б', off: 'б' },
    eng: { on: '<', off: ',' },
  },
  { name: 'Period',
    class: 'key',
    row: 3,
    item: 9,
    ru: { on: 'Ю', off: 'ю' },
    eng: { on: '>', off: '.' },
  },
  { name: 'Slash',
    class: 'key',
    row: 3,
    item: 10,
    ru: { on: ',', off: '.' },
    eng: { on: '?', off: '/' },
  },
  { name: 'ArrowUp',
    class: 'key special-key arr-top',
    row: 3,
    item: 11,
    ru: { on: '▲', off: '▲' },
    eng: { on: '▲', off: '▲' },
  },
  { name: 'ShiftRight',
    class: 'key special-key shiftR',
    row: 3,
    item: 12,
    ru: { on: 'shift', off: 'shift' },
    eng: { on: 'shift', off: 'shift' },
  },
  { name: 'ControlLeft',
    class: 'key special-key ctrl',
    row: 4,
    item: 0,
    ru: { on: 'ctrl', off: 'ctrl' },
    eng: { on: 'ctrl', off: 'ctrl' },
  },
  { name: 'MetaLeft',
    class: 'key special-key win',
    row: 4,
    item: 1,
    ru: { on: 'win', off: 'win' },
    eng: { on: 'win', off: 'win' },
  },
  { name: 'AltLeft',
    class: 'key special-key alt',
    row: 4,
    item: 2,
    ru: { on: 'alt', off: 'alt' },
    eng: { on: 'alt', off: 'alt' },
  },
  { name: 'Space',
    class: 'key special-key space',
    row: 4,
    item: 3,
    ru: { on: ' ', off: ' ' },
    eng: { on: ' ', off: ' ' },
  },
  { name: 'AltRight',
    class: 'key special-key alt',
    row: 4,
    item: 4,
    ru: { on: 'alt', off: 'alt' },
    eng: { on: 'alt', off: 'alt' },
  },
  { name: 'ArrowLeft',
    class: 'key special-key arr-left',
    row: 4,
    item: 5,
    ru: { on: '◀', off: '◀' },
    eng: { on: '◀', off: '◀' },
  },
  { name: 'ArrowDown',
    class: 'key special-key arr-down',
    row: 4,
    item: 6,
    ru: { on: '▼', off: '▼' },
    eng: { on: '▼', off: '▼' },
  },
  { name: 'ArrowRight',
    class: 'key special-key arr-right',
    row: 4,
    item: 7,
    ru: { on: '▶', off: '▶' },
    eng: { on: '▶', off: '▶' },
  },
  { name: 'ControlRight',
    class: 'key special-key ctrl',
    row: 4,
    item: 8,
    ru: { on: 'ctrl', off: 'ctrl' },
    eng: { on: 'ctrl', off: 'ctrl' },
  },
];
